# Generated by Django 4.2.11 on 2024-06-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_movimento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='quantidade',
            field=models.DecimalField(db_comment='Quantidade movimentada', decimal_places=5, max_digits=9),
        ),
    ]
